//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Mobile.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Church.Mobile.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar ubicación.
        /// </summary>
        internal static string action_add_latlng {
            get {
                return ResourceManager.GetString("action_add_latlng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Nuevo correo.
        /// </summary>
        internal static string action_add_new_fiscal_email {
            get {
                return ResourceManager.GetString("action_add_new_fiscal_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Nueva dirección.
        /// </summary>
        internal static string action_add_newaddress {
            get {
                return ResourceManager.GetString("action_add_newaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar al pedido.
        /// </summary>
        internal static string action_add_product {
            get {
                return ResourceManager.GetString("action_add_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        internal static string action_back {
            get {
                return ResourceManager.GetString("action_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar orden.
        /// </summary>
        internal static string action_cancel_order {
            get {
                return ResourceManager.GetString("action_cancel_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        internal static string action_change_password {
            get {
                return ResourceManager.GetString("action_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string action_continue {
            get {
                return ResourceManager.GetString("action_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar orden.
        /// </summary>
        internal static string action_create_order {
            get {
                return ResourceManager.GetString("action_create_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string action_login {
            get {
                return ResourceManager.GetString("action_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string action_next {
            get {
                return ResourceManager.GetString("action_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string action_ok {
            get {
                return ResourceManager.GetString("action_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea cuenta.
        /// </summary>
        internal static string action_register {
            get {
                return ResourceManager.GetString("action_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string action_save {
            get {
                return ResourceManager.GetString("action_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y continuar.
        /// </summary>
        internal static string action_save_address {
            get {
                return ResourceManager.GetString("action_save_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De momento solo estamos llegando a Tijuana, Tecate y Rosarito. .
        /// </summary>
        internal static string alert_towns {
            get {
                return ResourceManager.GetString("alert_towns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese la direccion fiscal.
        /// </summary>
        internal static string error_bill_address {
            get {
                return ResourceManager.GetString("error_bill_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione una colonia..
        /// </summary>
        internal static string error_billarea {
            get {
                return ResourceManager.GetString("error_billarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione un estado..
        /// </summary>
        internal static string error_billstate {
            get {
                return ResourceManager.GetString("error_billstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione una ciudad..
        /// </summary>
        internal static string error_billtown {
            get {
                return ResourceManager.GetString("error_billtown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de crear al menos una dirección..
        /// </summary>
        internal static string error_create_address {
            get {
                return ResourceManager.GetString("error_create_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email ingresado no es válido..
        /// </summary>
        internal static string error_email_invalid {
            get {
                return ResourceManager.GetString("error_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de completar los campos requeridos..
        /// </summary>
        internal static string error_enter_required_fields {
            get {
                return ResourceManager.GetString("error_enter_required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de ingresar al menos un correo de facturación..
        /// </summary>
        internal static string error_fiscal_emails_needed {
            get {
                return ResourceManager.GetString("error_fiscal_emails_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener datos del servidor.
        /// </summary>
        internal static string error_getting_data {
            get {
                return ResourceManager.GetString("error_getting_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta..
        /// </summary>
        internal static string error_invalid_password {
            get {
                return ResourceManager.GetString("error_invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click en Confirmar Ubicación para poder continuar.
        /// </summary>
        internal static string error_location_verification_required {
            get {
                return ResourceManager.GetString("error_location_verification_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes acceso a Internet.
        /// </summary>
        internal static string error_network_unavailable {
            get {
                return ResourceManager.GetString("error_network_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha agregado productos..
        /// </summary>
        internal static string error_no_products_added {
            get {
                return ResourceManager.GetString("error_no_products_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener al menos 6 caracteres con una combinación de mayúsculas, minúsculas y números..
        /// </summary>
        internal static string error_password_not_valid {
            get {
                return ResourceManager.GetString("error_password_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es requerida..
        /// </summary>
        internal static string error_password_required {
            get {
                return ResourceManager.GetString("error_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario habilitar los permisos para brindarle un mejor servicio..
        /// </summary>
        internal static string error_permissions {
            get {
                return ResourceManager.GetString("error_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de ingresar RFC valido..
        /// </summary>
        internal static string error_rfc_invalid {
            get {
                return ResourceManager.GetString("error_rfc_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error, intente de nuevo mas tarde..
        /// </summary>
        internal static string error_try_again {
            get {
                return ResourceManager.GetString("error_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe..
        /// </summary>
        internal static string error_user_not_found {
            get {
                return ResourceManager.GetString("error_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario es requerido..
        /// </summary>
        internal static string error_username_required {
            get {
                return ResourceManager.GetString("error_username_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es invalido..
        /// </summary>
        internal static string error_value_not_valid {
            get {
                return ResourceManager.GetString("error_value_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es requerido..
        /// </summary>
        internal static string error_value_required {
            get {
                return ResourceManager.GetString("error_value_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título de la dirección.
        /// </summary>
        internal static string hint_address_name {
            get {
                return ResourceManager.GetString("hint_address_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia.
        /// </summary>
        internal static string hint_area {
            get {
                return ResourceManager.GetString("hint_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre calles.
        /// </summary>
        internal static string hint_betweenStreets {
            get {
                return ResourceManager.GetString("hint_betweenStreets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección fiscal *.
        /// </summary>
        internal static string hint_billAddress {
            get {
                return ResourceManager.GetString("hint_billAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edificio.
        /// </summary>
        internal static string hint_building {
            get {
                return ResourceManager.GetString("hint_building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón social *.
        /// </summary>
        internal static string hint_businessName {
            get {
                return ResourceManager.GetString("hint_businessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular *.
        /// </summary>
        internal static string hint_cellphone {
            get {
                return ResourceManager.GetString("hint_cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo *.
        /// </summary>
        internal static string hint_email {
            get {
                return ResourceManager.GetString("hint_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número exterior *.
        /// </summary>
        internal static string hint_externalNumber {
            get {
                return ResourceManager.GetString("hint_externalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número interior.
        /// </summary>
        internal static string hint_internalNumber {
            get {
                return ResourceManager.GetString("hint_internalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesos.
        /// </summary>
        internal static string hint_money {
            get {
                return ResourceManager.GetString("hint_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido materno.
        /// </summary>
        internal static string hint_msurname {
            get {
                return ResourceManager.GetString("hint_msurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre *.
        /// </summary>
        internal static string hint_name {
            get {
                return ResourceManager.GetString("hint_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplo (Mi casa, Restaurante).
        /// </summary>
        internal static string hint_name_opts {
            get {
                return ResourceManager.GetString("hint_name_opts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña *.
        /// </summary>
        internal static string hint_password {
            get {
                return ResourceManager.GetString("hint_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string hint_phone {
            get {
                return ResourceManager.GetString("hint_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal *.
        /// </summary>
        internal static string hint_postalCode {
            get {
                return ResourceManager.GetString("hint_postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privada o coto.
        /// </summary>
        internal static string hint_private {
            get {
                return ResourceManager.GetString("hint_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido paterno *.
        /// </summary>
        internal static string hint_psurname {
            get {
                return ResourceManager.GetString("hint_psurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        internal static string hint_quantity {
            get {
                return ResourceManager.GetString("hint_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias.
        /// </summary>
        internal static string hint_references {
            get {
                return ResourceManager.GetString("hint_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC *.
        /// </summary>
        internal static string hint_rfc {
            get {
                return ResourceManager.GetString("hint_rfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si se sabe su número de SAP escribablo aqui.
        /// </summary>
        internal static string hint_sap_number {
            get {
                return ResourceManager.GetString("hint_sap_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string hint_sector {
            get {
                return ResourceManager.GetString("hint_sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        internal static string hint_select_address {
            get {
                return ResourceManager.GetString("hint_select_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string hint_states {
            get {
                return ResourceManager.GetString("hint_states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle *.
        /// </summary>
        internal static string hint_street {
            get {
                return ResourceManager.GetString("hint_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        internal static string hint_town {
            get {
                return ResourceManager.GetString("hint_town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre comercial.
        /// </summary>
        internal static string hint_tradeName {
            get {
                return ResourceManager.GetString("hint_tradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string hint_username {
            get {
                return ResourceManager.GetString("hint_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu usuario es tu numero de telefono.
        /// </summary>
        internal static string hint_username_phone {
            get {
                return ResourceManager.GetString("hint_username_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Requiere factura?.
        /// </summary>
        internal static string label_bill_required {
            get {
                return ResourceManager.GetString("label_bill_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar nueva contraseña.
        /// </summary>
        internal static string label_confirm_password {
            get {
                return ResourceManager.GetString("label_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        internal static string label_current_password {
            get {
                return ResourceManager.GetString("label_current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi contraseña.
        /// </summary>
        internal static string label_forgot_password {
            get {
                return ResourceManager.GetString("label_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión.
        /// </summary>
        internal static string label_login {
            get {
                return ResourceManager.GetString("label_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        internal static string label_new_password {
            get {
                return ResourceManager.GetString("label_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string label_password {
            get {
                return ResourceManager.GetString("label_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string label_select_product {
            get {
                return ResourceManager.GetString("label_select_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Que tipo de servicio necesita?.
        /// </summary>
        internal static string label_select_service {
            get {
                return ResourceManager.GetString("label_select_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Utilizar dirección existente?.
        /// </summary>
        internal static string label_use_current_address {
            get {
                return ResourceManager.GetString("label_use_current_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string label_username {
            get {
                return ResourceManager.GetString("label_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string label_welcome {
            get {
                return ResourceManager.GetString("label_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron direcciones..
        /// </summary>
        internal static string msg_ev_address {
            get {
                return ResourceManager.GetString("msg_ev_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ordenes nuevas..
        /// </summary>
        internal static string msg_ev_orders {
            get {
                return ResourceManager.GetString("msg_ev_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta.
        /// </summary>
        internal static string option_card {
            get {
                return ResourceManager.GetString("option_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectivo.
        /// </summary>
        internal static string option_cash {
            get {
                return ResourceManager.GetString("option_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparto.
        /// </summary>
        internal static string option_distribution {
            get {
                return ResourceManager.GetString("option_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesos.
        /// </summary>
        internal static string option_money {
            get {
                return ResourceManager.GetString("option_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string option_no {
            get {
                return ResourceManager.GetString("option_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litros.
        /// </summary>
        internal static string option_qty {
            get {
                return ResourceManager.GetString("option_qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacionario.
        /// </summary>
        internal static string option_stationary {
            get {
                return ResourceManager.GetString("option_stationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string option_yes {
            get {
                return ResourceManager.GetString("option_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección guardada existosamente..
        /// </summary>
        internal static string success_creating_address {
            get {
                return ResourceManager.GetString("success_creating_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo guardado existosamente..
        /// </summary>
        internal static string success_creating_fiscal_email {
            get {
                return ResourceManager.GetString("success_creating_fiscal_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección guardada existosamente..
        /// </summary>
        internal static string success_editing_address {
            get {
                return ResourceManager.GetString("success_editing_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación guardada existosamente..
        /// </summary>
        internal static string success_editing_location {
            get {
                return ResourceManager.GetString("success_editing_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi cuenta.
        /// </summary>
        internal static string tab1_title {
            get {
                return ResourceManager.GetString("tab1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva orden.
        /// </summary>
        internal static string tab2_title {
            get {
                return ResourceManager.GetString("tab2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis ordenes.
        /// </summary>
        internal static string tab3_title {
            get {
                return ResourceManager.GetString("tab3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de entrega.
        /// </summary>
        internal static string title_address_selected {
            get {
                return ResourceManager.GetString("title_address_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        internal static string title_addresses {
            get {
                return ResourceManager.GetString("title_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos fiscales.
        /// </summary>
        internal static string title_bill_addresses {
            get {
                return ResourceManager.GetString("title_bill_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales.
        /// </summary>
        internal static string title_credentials {
            get {
                return ResourceManager.GetString("title_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chofer.
        /// </summary>
        internal static string title_driver {
            get {
                return ResourceManager.GetString("title_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        internal static string title_folio {
            get {
                return ResourceManager.GetString("title_folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string title_frag1 {
            get {
                return ResourceManager.GetString("title_frag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        internal static string title_frag2 {
            get {
                return ResourceManager.GetString("title_frag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmacion.
        /// </summary>
        internal static string title_frag3 {
            get {
                return ResourceManager.GetString("title_frag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos generales.
        /// </summary>
        internal static string title_general_data {
            get {
                return ResourceManager.GetString("title_general_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia Sesion.
        /// </summary>
        internal static string title_login {
            get {
                return ResourceManager.GetString("title_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio.
        /// </summary>
        internal static string title_my_address_selected {
            get {
                return ResourceManager.GetString("title_my_address_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de pago.
        /// </summary>
        internal static string title_my_payment_method {
            get {
                return ResourceManager.GetString("title_my_payment_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi orden.
        /// </summary>
        internal static string title_order_confirmation {
            get {
                return ResourceManager.GetString("title_order_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha programada.
        /// </summary>
        internal static string title_order_date {
            get {
                return ResourceManager.GetString("title_order_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string title_order_note {
            get {
                return ResourceManager.GetString("title_order_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        internal static string title_order_status {
            get {
                return ResourceManager.GetString("title_order_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string title_order_total {
            get {
                return ResourceManager.GetString("title_order_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos adicionales.
        /// </summary>
        internal static string title_orders_extras {
            get {
                return ResourceManager.GetString("title_orders_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string title_products {
            get {
                return ResourceManager.GetString("title_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        internal static string title_select_service {
            get {
                return ResourceManager.GetString("title_select_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos pago.
        /// </summary>
        internal static string title_tab_payment {
            get {
                return ResourceManager.GetString("title_tab_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver ubicación.
        /// </summary>
        internal static string title_track {
            get {
                return ResourceManager.GetString("title_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string title_welcome {
            get {
                return ResourceManager.GetString("title_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej. &quot;Casa de la abuela&quot;, &quot;Mi casa&quot;, &quot;Casa de Verano&quot;.
        /// </summary>
        internal static string tooltip_address_name {
            get {
                return ResourceManager.GetString("tooltip_address_name", resourceCulture);
            }
        }
    }
}
